<?xml version="1.0" encoding="utf-8" standalone="yes"?>
<rss version="2.0" xmlns:atom="http://www.w3.org/2005/Atom">
  <channel>
    <title>error on 打工人日志</title>
    <link>https://www.jobcher.com/tags/error/</link>
    <description>Recent content in error on 打工人日志</description>
    <generator>Hugo -- gohugo.io</generator>
    <language>en-us</language>
    <lastBuildDate>Thu, 10 Aug 2023 00:00:00 +0000</lastBuildDate><atom:link href="https://www.jobcher.com/tags/error/index.xml" rel="self" type="application/rss+xml" />
    <item>
      <title>Vue3 &#43; vite &#43; nginx项目部署后404问题</title>
      <link>https://www.jobcher.com/posts/error/nginx-error/</link>
      <pubDate>Thu, 10 Aug 2023 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/nginx-error/</guid>
      <description>Vue3 + vite + nginx项目部署后404问题 vue3 + vite + nginx
在服务器上部署后打开首页都没问题，打开其他路径全部 404。
nginx 报错日志：No such file or directory
其实查看 build 后的dist文件夹可以发现，只有一个index.html，当你访问别的路径时nignx查找不到所以就报错了
解决方案 在 nginx.conf 中添加: try_files $uri $uri/ /index.html;
server { listen 80; server_name localhost; location / { root /dist; index index.html index.htm; # 在配置文件的此处加上这句话 try_files $uri $uri/ /index.html; } } 总结 其实上述改动就是告诉 nignx 找不到文件的时候就访问 index.html 就可以了。
究其原因其实就是是 vue3 的 router 使用了history模式，该模式与之前hash模式的具体区别可以自行百度一下，不在此赘述。</description>
    </item>
    
    <item>
      <title>githubAction set-output弃用错误</title>
      <link>https://www.jobcher.com/posts/error/github-error/</link>
      <pubDate>Fri, 21 Oct 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/github-error/</guid>
      <description>githubAction set-output 弃用错误 The set-output command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
原因 如果您有一个使用 设置输出的GitHub Actionsecho ::set-output key=value工作流程，您已经开始看到无用的弃用警告。这是修复它的方法。查看官方链接基本上得不到什么帮助！
修复方法 更新其它人的 action 方法 将 @actions/core 提升到 1.10.0 修改自己的 aciton 方法 run: echo &amp;#34;::set-output name=KEY::VALUE&amp;#34; ## 改为 run: echo &amp;#34;KEY=VALUE&amp;#34; &amp;gt;&amp;gt;$GITHUB_OUTPUT 建议：使用自己的方法
总结 平台经营者非常肆意妄为的修改自己的代码内容弃用功能，无限的权力滋生傲慢……我相信大部分开发这并没有注意到这个告警，知道流水线服务报错之后才会注意到，希望微软可以对能更加包容不同的开发者，尊重开发者社区。</description>
    </item>
    
    <item>
      <title>k8s CNI 问题 连接认证失效</title>
      <link>https://www.jobcher.com/posts/error/k8s-error2/</link>
      <pubDate>Fri, 23 Sep 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/k8s-error2/</guid>
      <description>k8s CNI 问题 连接认证失效 删除 calico 换成 flannel 后，容器没有正常启动
network: error getting ClusterInformation: connection is unauthorized: Unauthorized]
解决问题 删除掉 /etc/cni/net.d/ 目录下的 calico 配置文件即可。
要删除所有节点的配置文件
sudo rm -rf /etc/cni/net.d/*calico* 不要重复网络插件 </description>
    </item>
    
    <item>
      <title>k8s.gcr.io国内无法连接解决方法</title>
      <link>https://www.jobcher.com/posts/error/k8s-error3/</link>
      <pubDate>Thu, 22 Sep 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/k8s-error3/</guid>
      <description>k8s.gcr.io 国内无法连接解决方法 Get https://k8s.gcr.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)
这个一看知道什么原因了，应该 GFW！那好吧，只能给 docker 加个代理了。
解决问题 添加 mirror 站点
registry.cn-hangzhou.aliyuncs.com/google_containers </description>
    </item>
    
    <item>
      <title>K8S 问题排查：cgroup 内存泄露问题</title>
      <link>https://www.jobcher.com/posts/error/k8s-error/</link>
      <pubDate>Tue, 30 Aug 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/k8s-error/</guid>
      <description>K8S 问题排查：cgroup 内存泄露问题 unable to ensure pod container exists: failed to create container for [kubepods besteffort pod5f26dae8-0421-4eab-a3f7-aa51c6848e2b] : mkdir /sys/fs/cgroup/memory/kubepods/besteffort/pod5f26dae8-0421-4eab-a3f7-aa51c6848e2b: cannot allocate memory 查看 linux 内核 cat /proc/version uname -a 可以发现 linux 版本是 3.0 版本
原因 cgroup 的 kmem account 特性在 Linux 3.x 内核上有内存泄露问题，然后k8s用了这个特性，导致后面创建不出新的pod来了
解决方法 # 修改/etc/default/grub 为 GRUB_CMDLINE_LINUX=&amp;#34;crashkernel=auto rd.lvm.lv=centos/root rd.lvm.lv=centos/swap rhgb quiet cgroup.memory=nokmem&amp;#34; #加上了 cgroup.memory=nokmem # 生成配置 /usr/sbin/grub2-mkconfig -o /boot/grub2/grub.cfg # 重启机器 reboot 验证 cat /sys/fs/cgroup/memory/kubepods/burstable/pod*/*/memory.kmem.slabinfo 输出信息
cat: /sys/fs/cgroup/memory/kubepods/burstable/pod0fe273ca-42e0-4223-9fe8-16d8dd1774e9/0fdd5d9c16929fd600dbdf313b5c3ebabad912dc0cb076ed6e7799e028b31481/memory.kmem.slabinfo: 输入/输出错误 cat: /sys/fs/cgroup/memory/kubepods/burstable/pod0fe273ca-42e0-4223-9fe8-16d8dd1774e9/aa30198d0c5413b70bf488c9daa350a85c7fc6b677235c5adaf2dde6caf95ec4/memory.</description>
    </item>
    
    <item>
      <title>docker 问题处理</title>
      <link>https://www.jobcher.com/posts/error/docker-error/</link>
      <pubDate>Thu, 04 Aug 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/docker-error/</guid>
      <description>docker 无法启动 打开服务器输入docker ps,输出错误
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
怀疑是不是docker.services 部署没成功，systemctl start docker 启动 docker，结果服务器还是报错
Job for docker.service failed because the control process exited with error code.
See &amp;ldquo;systemctl status docker.service&amp;rdquo; and &amp;ldquo;journalctl -xe&amp;rdquo; for details.
systemctl status docker.service 输出日志：
● docker.service - Docker Application Container Engine Loaded: loaded (/lib/systemd/system/docker.service; enabled; vendor preset: enabled) Active: failed (Result: exit-code) since Thu 2022-08-04 11:43:05 CST; 2min 57s ago TriggeredBy: ● docker.</description>
    </item>
    
    <item>
      <title>ProXmoX VE升级 apt-get update 报错</title>
      <link>https://www.jobcher.com/posts/error/pveupdate/</link>
      <pubDate>Sun, 30 Jan 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/pveupdate/</guid>
      <description>ProXmoX VE 升级 apt-get update 报错 解决方法 vim /etc/apt/sources.list.d/pve-enterprise.list #注释掉 #deb https://enterprise.proxmox.com/debian/pve stretch pve-enterprise 添加内容 echo &amp;#34;deb http://download.proxmox.com/debian/pve stretch pve-no-subscription&amp;#34; &amp;gt; /etc/apt/sources.list.d/pve-install-repo.list wget http://download.proxmox.com/debian/proxmox-ve-release-5.x.gpg -O /etc/apt/trusted.gpg.d/proxmox-ve-release-5.x.gpg 更新系统 apt update &amp;amp;&amp;amp; apt dist-upgrade 结尾 升级完成后，可以执行pveversion -v查看下最新的软件版本。然后执行reboot重启物理服务器</description>
    </item>
    
    <item>
      <title>安装 docker 出现 ERROR: Unsupported distribution &#39;ol&#39; 问题</title>
      <link>https://www.jobcher.com/posts/error/error1/</link>
      <pubDate>Tue, 11 Jan 2022 00:00:00 +0000</pubDate>
      
      <guid>https://www.jobcher.com/posts/error/error1/</guid>
      <description>安装 docker 出现 ERROR: Unsupported distribution &amp;lsquo;ol&amp;rsquo; 问题 部署 docker 安装出现 ERROR: Unsupported distribution &amp;lsquo;ol&amp;rsquo;
确认是不是 arm 架构 uname -r 确认使用的是不是 oracle 服务器系统,如果是请继续操作，安装依赖： dnf install -y dnf-utils zip unzip dnf config-manager --add-repo=https://download.docker.com/linux/centos/docker-ce.repo 安装 docker dnf remove -y runc dnf install -y docker-ce --nobest 完成 docker 安装并检查 systemctl enable docker.service systemctl start docker.service #检查 systemctl status docker.service docker info docker version 结尾 该问题主要是 oracle 没有支持依赖导致的~oracle 还是很不错的~</description>
    </item>
    
  </channel>
</rss>
